spring:
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:validate}
    properties:
      hibernate:
        format_sql: ${JPA_FORMAT_SQL:false}
    show-sql: ${JPA_SHOW_SQL:false}

app:
  cors:
    allowed-origin-patterns: ${CORS_ALLOWED_ORIGIN_PATTERNS}
