package com.example.movra.bc.analytics.activation_event.domain.type;

public enum AnalyticsEventType {
    SIGNUP,
    ONBOARDING_STARTED,
    ONBOARDING_SKIPPED,
    BEHAVIOR_PROFILE_CREATED,
    FUTURE_VISION_CREATED,
    MORNING_TASK_CREATED,
    TOP_PICK_SELECTED,
    TIMETABLE_SLOT_CREATED,
    FOCUS_SESSION_STARTED,
    FOCUS_SESSION_COMPLETED,
    FOCUS_SESSION_ABANDONED,
    TINY_WIN_CREATED,
    DAILY_REFLECTION_CREATED,
    RECOVERY_CARD_VIEWED,
    RECOVERY_CARD_ACTIONED,
    ACCOUNTABILITY_INVITE_SENT,
    ACCOUNTABILITY_FRIEND_JOINED,
    WEB_PUSH_OPT_IN,
    SCHOOL_HOURS_MUTE_TOGGLED,
    EXAM_REGISTERED
}
